# Generated by Django 5.0.14 on 2025-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('seniority', models.CharField(choices=[('Junior', 'Junior'), ('Semi', 'Semi'), ('Senior', 'Senior')], max_length=20)),
                ('modality', models.CharField(choices=[('Remoto', 'Remoto'), ('Híbrido', 'Híbrido'), ('Presencial', 'Presencial')], max_length=20)),
                ('schedule', models.CharField(default='Completa', max_length=20)),
                ('location', models.CharField(default='Chile', max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CLP', 'CLP')], default='USD', max_length=3)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
